#!/bin/sh
file=$1
w=$2
h=$3
x=$4
y=$(($5 + 1))

filetype="$(file -Lb --mime-type "$file")"

case "$filetype" in
image*)
	kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "$file" </dev/null >/dev/tty
	exit 1
	;;
video*)
	# vidthumb is from here:
	# https://raw.githubusercontent.com/duganchen/kitty-pistol-previewer/main/vidthumb
	kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "$(vidthumb "$file")" </dev/null >/dev/tty
	exit 1
	;;
esac

pistol "$file"
