#!hint/zsh

local bold="$(tput bold)"
local purple="$(tput setaf 5)"
local white="$(tput setaf 15)"
local green="$(tput setaf 2)"
local reset="$(tput sgr0)"
local civis="$(tput civis)"
local cnorm="$(tput cnorm)"

printf "$civis"

function TRAPINT {
	printf "$cnorm"
}

printf 'zsh: command not found: %s\n' "$1"
printf "$bold$1$reset may be found in the following packages:"

local oldname pkgname pkgver cmdpath
while read -r -d $'\0' pkgname pkgver cmdpath
do
	[[ -z "$oldname" ]] &&
		printf "\n"
	[[ "$oldname" != "$pkgname" ]] &&
		printf "$bold$purple%s/$white%s $green%s$reset\n" "${(s:/:)pkgname}" "$pkgver"
	printf "    %s\n" "$cmdpath"
	oldname="$pkgname"
done <<<"$(/usr/bin/pkgfile -0 -v -q -w -- "$1" 2>/dev/null)"

if [[ -z "$oldname" ]]
then
	printf '\r'
fi

printf "$cnorm"
