#!hint/zsh

local bold="$(tput bold)"
local purple="$(tput setaf 5)"
local white="$(tput setaf 15)"
local green="$(tput setaf 2)"
local reset="$(tput sgr0)"
local civis="$(tput civis)"
local cnorm="$(tput cnorm)"

printf "${civis}"

function TRAPINT {
	tput cnorm
}

printf 'zsh: command not found: %s\n' "$1"
printf "${bold}$1${reset} may be found in the following packages:"

local entries=(
	${(0)"$(/usr/bin/pkgfile -0 -b "$1")"}
)

if ((${#entries[@]}))
then
	printf "\n"

	for entry in "${entries[@]}"
	do
		# (repo package)
		local fields=(
			${(ps:/:)entry}
		)

		printf "${bold}${purple}%s/${white}%s${reset}\n" "${fields[1]}" "${fields[2]}"
	done

	printf "${cnorm}"
	return
fi

printf "\r${cnorm}"
