theme = "rasmus"

[editor]
auto-save = true
bufferline = "always"
color-modes = true
completion-trigger-len = 1
line-number = "relative"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "hidden"

[editor.indent-guides]
render = true
character = "|"

[keys.normal]
"backspace" = ":buffer-close"
"q" = ":quit"
"Q" = ":quit"
