theme = "nord"

[editor]
color-modes = true

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
render = true
character = "|"

[editor.whitespace.render]
tab = "none"
space = "none"

[keys.normal]
"backspace" = ":bc"

