theme = "nord"

[editor]
auto-completion = true
auto-format = true
auto-info = true
bufferline = "always"
color-modes = true

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
render = true
character = "|"

[editor.whitespace.render]
tab = "none"
space = "none"

[keys.normal]
"backspace" = ":bc"
"q" = ":q"
"Q" = ":q"

